### ISSUE TITLE
CHữa bài tập tuần 1

### ISSUE THREAD

**Issue by PhanThanhTrung** [sonktpm3/SonKtpm3#1]
### Thứ 1:

Trong thư mục Week1 của em vẫn còn file .exe thường thì chúng ta k commit file đó git cũng sẽ không theo dõi file đó luôn. Lý do là do em chưa có file .gitignore nên là git n vẫn theo dõi file .exe em thêm file .gitignore vào cho anh nhé. Ngoài ra thì trong thư mục week 1 của em chưa có file readme, thêm vào nhé.

### Thứ 2:

Cố gắng viết readme cho đẹp vào em nhé, càng chi tiết càng tốt. Có thể tham khảo trên mạng đó e.

### Thứ 3:

Khi em commit để sửa bài tập thì hãy link commit đó đến đây bằng các thêm vào message khi commit là Fix + Mã của issue( mã của issue này là #1 nhé) để link. CHúc em làm bài vui vẻ :v

**Comment by sonktpm3** [comment]
https://github.com/sonktpm3/SonKtpm3.git
em ko biết e đã làm đúng chưa ạ ??? e dùng git rm -r --cached [/path/to/folder] để xóa file đó , e có tạo file .gitignore nhưng e push thì ko thấy lên ạ ?? còn cái message khi commit thì e quên ghi luôn ??

**Comment by PhanThanhTrung** [comment]
Em vẫn chưa có readme ở trong folder week 1
